weights: yolov5s.pt
cfg: /home/luke/project/yolov5/models/yolov5xs_wider_face_c3.yaml
data: /home/luke/project/yolov5/data/yolov5xs_wider_face.yaml
hyp: data/hyp.scratch.yaml
epochs: 99999
batch_size: 64
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 24
project: runs/train
entity: null
name: 640_wider_face_c3_yolov5xs
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/640_wider_face_c3_yolov5xs5
total_batch_size: 64
